# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys

import time
localtime=time.asctime(time.localtime(time.time()))
from firebase import firebase


a = sys.argv[1:]
# name = a[0][1:]
# mobileNo = a[1]
# idSelected  = a[2]
name = "Shubha Jadhao"
mobileNo = "9822"
idSelected = "406145"


firebase = firebase.FirebaseApplication('https://m-card-2ac54.firebaseio.com/', None)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1440, 807)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1441, 901))
        self.frame.setStyleSheet("background-color:rgb(3, 14, 23)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(1110, 10, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(204, 206, 206)")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(1260, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(223, 226, 226)\n"
"")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(270, 110, 1181, 661))
        self.frame_2.setStyleSheet("background-color:rgb(12, 26, 42)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 340, 1181, 321))
        self.frame_3.setStyleSheet("background-color:rgb(252, 255, 255)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.saveprescriptionbutton = QtWidgets.QPushButton(self.frame_3)
        self.saveprescriptionbutton.setGeometry(QtCore.QRect(850, 270, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveprescriptionbutton.setFont(font)
        self.saveprescriptionbutton.setStyleSheet("background-color:rgb(146, 35, 145);\n"
"color:rgb(255,255,255)")
        self.saveprescriptionbutton.setObjectName("saveprescriptionbutton")
        self.label_19 = QtWidgets.QLabel(self.frame_3)
        self.label_19.setGeometry(QtCore.QRect(20, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb((131, 133, 133))\n"
"\n"
"")
        self.label_19.setObjectName("label_19")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_3)
        self.scrollArea.setGeometry(QtCore.QRect(20, 50, 1141, 211))
        self.scrollArea.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1139, 209))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.nameScrollArea = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.nameScrollArea.setGeometry(QtCore.QRect(10, 30, 341, 171))
        self.nameScrollArea.setWidgetResizable(True)
        self.nameScrollArea.setObjectName("nameScrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 339, 169))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.nameScrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.addWedgets = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.addWedgets.setGeometry(QtCore.QRect(1060, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addWedgets.setFont(font)
        self.addWedgets.setStyleSheet("background-color:rgb(146, 35, 145);\n"
"color:rgb(255,255,255)")
        self.addWedgets.setObjectName("addWedgets")
        self.deleteWedgets = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.deleteWedgets.setGeometry(QtCore.QRect(1060,45,70,31))
        self.deleteWedgets.setFont(font)
        self.deleteWedgets.setStyleSheet("background-color:rgb(146, 35, 145);\n"
"color:rgb(255,255,255)")
        self.deleteWedgets.setObjectName("deleteWedgets")

        self.timeScrollArea = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.timeScrollArea.setGeometry(QtCore.QRect(360, 30, 341, 171))
        self.timeScrollArea.setWidgetResizable(True)
        self.timeScrollArea.setObjectName("timeScrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 339, 169))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.timeScrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.quantityScrollArea = QtWidgets.QScrollArea(self.scrollAreaWidgetContents)
        self.quantityScrollArea.setGeometry(QtCore.QRect(710, 30, 341, 171))
        self.quantityScrollArea.setWidgetResizable(True)
        self.quantityScrollArea.setObjectName("quantityScrollArea")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 339, 169))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.quantityScrollArea.setWidget(self.scrollAreaWidgetContents_5)
        self.label_20 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:rgb(128, 130, 130)")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setGeometry(QtCore.QRect(360, 10, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:rgb(128, 130, 130)")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setGeometry(QtCore.QRect(710, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:rgb(128, 130, 130)")
        self.label_22.setObjectName("label_22")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(600, 0, 2, 340))
        self.frame_4.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(620, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(0, 233, 222)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(0, 233, 222)")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(20, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(245, 248, 247)")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(20, 160, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(245, 248, 247)")
        self.label_9.setObjectName("label_9")
        self.diseasename = QtWidgets.QTextEdit(self.frame_2)
        self.diseasename.setGeometry(QtCore.QRect(20, 110, 311, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.diseasename.setFont(font)
        self.diseasename.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"color:rgb(103, 104, 104)")
        self.diseasename.setObjectName("diseasename")
        self.prescriptionnolabel = QtWidgets.QLabel(self.frame_2)
        self.prescriptionnolabel.setGeometry(QtCore.QRect(20, 240, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.prescriptionnolabel.setFont(font)
        self.prescriptionnolabel.setStyleSheet("color:rgb(245, 248, 247)")
        self.prescriptionnolabel.setObjectName("prescriptionnolabel")
        self.prescriptionHistoryutton = QtWidgets.QPushButton(self.frame_2)
        self.prescriptionHistoryutton.setGeometry(QtCore.QRect(20, 280, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.prescriptionHistoryutton.setFont(font)
        self.prescriptionHistoryutton.setStyleSheet("background-color:rgb(146, 35, 145);\n"
"color:rgb(255,255,255)")
        self.prescriptionHistoryutton.setObjectName("prescriptionHistoryutton")
        self.nameofpatient = QtWidgets.QLabel(self.frame_2)
        self.nameofpatient.setGeometry(QtCore.QRect(620, 80, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.nameofpatient.setFont(font)
        self.nameofpatient.setStyleSheet("color:rgb(245, 248, 247)")
        self.nameofpatient.setObjectName("nameofpatient")
        self.namelabel = QtWidgets.QLabel(self.frame_2)
        self.namelabel.setGeometry(QtCore.QRect(750, 80, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.namelabel.setFont(font)
        self.namelabel.setStyleSheet("color:rgb(245, 248, 247)")
        self.namelabel.setObjectName("namelabel")
        self.mobilenoofpatient = QtWidgets.QLabel(self.frame_2)
        self.mobilenoofpatient.setGeometry(QtCore.QRect(620, 120, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.mobilenoofpatient.setFont(font)
        self.mobilenoofpatient.setStyleSheet("color:rgb(245, 248, 247)")
        self.mobilenoofpatient.setObjectName("mobilenoofpatient")
        self.mobnoLabel = QtWidgets.QLabel(self.frame_2)
        self.mobnoLabel.setGeometry(QtCore.QRect(750, 120, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.mobnoLabel.setFont(font)
        self.mobnoLabel.setStyleSheet("color:rgb(245, 248, 247)")
        self.mobnoLabel.setObjectName("mobnoLabel")
        self.bloodgroup = QtWidgets.QLabel(self.frame_2)
        self.bloodgroup.setGeometry(QtCore.QRect(620, 160, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bloodgroup.setFont(font)
        self.bloodgroup.setStyleSheet("color:rgb(245, 248, 247)")
        self.bloodgroup.setObjectName("bloodgroup")
        self.bloodgroupLabel = QtWidgets.QLabel(self.frame_2)
        self.bloodgroupLabel.setGeometry(QtCore.QRect(780, 160, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.bloodgroupLabel.setFont(font)
        self.bloodgroupLabel.setStyleSheet("color:rgb(245, 248, 247)")
        self.bloodgroupLabel.setObjectName("bloodgroupLabel")
        #self.address = QtWidgets.QLabel(self.frame_2)
        #self.address.setGeometry(QtCore.QRect(620, 200, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        #self.address.setFont(font)
        #self.address.setStyleSheet("color:rgb(245, 248, 247)")
        #self.address.setObjectName("address")
        #self.addresslabel = QtWidgets.QLabel(self.frame_2)
        
        #self.addresslabel.setGeometry(QtCore.QRect(740, 200, 421, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        #self.addresslabel.setFont(font)
        #self.addresslabel.setStyleSheet("color:rgb(245, 248, 247)")
        #self.addresslabel.setObjectName("addresslabel")
        self.dateEdit = QtWidgets.QDateEdit(self.frame_2)
        self.dateEdit.setGeometry(QtCore.QRect(18, 190, 331, 41))
        self.dateEdit.setStyleSheet("background-color:rgb(252, 255, 255)")
        self.dateEdit.setDate(QtCore.QDate.currentDate())
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 90, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(146, 35, 146)")
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(140, 90, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(30, 800, 151, 16))
        self.label_7.setStyleSheet("color:rgb(205, 208, 208)")
        self.label_7.setObjectName("label_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.addWedgets.clicked.connect(self.addWedgetsMethod)
        self.deleteWedgets.clicked.connect(self.deleteWedgetsMethod)

        self.nameOfDiArray =[]
        self.timeOfDiArray = []
        self.quantityOfDiArray = []

        self.nameBoxWedget = QtWidgets.QVBoxLayout()
        self.timeBoxWedget = QtWidgets.QVBoxLayout()
        self.quantityBoxWedget = QtWidgets.QVBoxLayout()

        self.nameLayout = QtWidgets.QWidget()
        self.timeLayout = QtWidgets.QWidget()
        self.quantityLayout = QtWidgets.QWidget()

        self.nameScrollArea.setStyleSheet("background-color:rgb(231, 231, 231)")
        self.timeScrollArea.setStyleSheet("background-color:rgb(231, 231, 231)")
        self.quantityScrollArea.setStyleSheet("background-color:rgb(231, 231, 231)")
        
        self.saveprescriptionbutton.clicked.connect(self.prescriptionSaveMethod)
        self.prescriptionHistoryutton.clicked.connect(self.prescriptionHistoryMethod)
        print(self.dateEdit.date().toPyDate())


    def prescriptionHistoryMethod(self):
            print("Hello")
            profileInfo = [name,mobileNo,idSelected]
            os.system("python thirdPage.py " + str(profileInfo))


            
    def addWedgetsMethod(self):
            self.nameTextField = QtWidgets.QTextEdit()
            font = QtGui.QFont()
            font.setPointSize(18)
            self.nameTextField.setFont(font)
            self.timeComboBox = QtWidgets.QComboBox()
            self.timeComboBox.addItem("Morning")
            self.timeComboBox.addItem("Afternoon")
            self.timeComboBox.addItem("Evening")
            self.timeComboBox.addItem("Morning,Evening")
            self.timeComboBox.addItem("Morning,Afternoon")
            self.timeComboBox.addItem("Afternoon,Evening")
            self.timeComboBox.addItem("Morning,Evening,Afternoon")
            self.timeComboBox.setFont(font)
            self.quantitySpinBox = QtWidgets.QSpinBox()
            self.quantitySpinBox.setFont(font)


            #set Property
            self.nameTextField.setStyleSheet("background-color:rgb(255, 255, 255)")
            self.timeComboBox.setStyleSheet("background-color:rgb(255, 255, 255)")
            self.quantitySpinBox.setStyleSheet("background-color:rgb(255, 255, 255)")
            
            self.nameBoxWedget.addWidget(self.nameTextField)
            self.nameLayout.setLayout(self.nameBoxWedget)
            self.nameOfDiArray.append(self.nameTextField)
            self.timeBoxWedget.addWidget(self.timeComboBox)
            self.timeLayout.setLayout(self.timeBoxWedget)
            self.timeOfDiArray.append(self.timeComboBox)
            self.quantityBoxWedget.addWidget(self.quantitySpinBox)
            self.quantityLayout.setLayout(self.quantityBoxWedget)
            self.quantityOfDiArray.append(self.quantitySpinBox)

            self.nameScrollArea.setWidget(self.nameLayout)
            self.timeScrollArea.setWidget(self.timeLayout)
            self.quantityScrollArea.setWidget(self.quantityLayout)
        

    
    def deleteWedgetsMethod(self):
            if len(self.nameOfDiArray) > 0:
                lenght = len(self.nameOfDiArray) - 1
                self.nameOfDiArray[lenght].deleteLater()
                self.nameOfDiArray[lenght] = None
                self.nameOfDiArray.pop(lenght)

                self.timeOfDiArray[lenght].deleteLater()
                self.timeOfDiArray[lenght] = None
                self.timeOfDiArray.pop(lenght)

                self.quantityOfDiArray[lenght].deleteLater()
                self.quantityOfDiArray[lenght] = None
                self.quantityOfDiArray.pop(lenght)
    def prescriptionSaveMethod(self):
            print(self.diseasename.toPlainText())
            dicti2 = {"1":self.diseasename.toPlainText()}

            for i in range(0,len(self.nameOfDiArray)):
                name = self.nameOfDiArray[i].toPlainText()
                time = self.timeOfDiArray[i].toPlainText()
                quantity = self.quantityOfDiArray[i].value()
                finalString = name + "_" + time + "_" + str(quantity)
                dicti2[str(i+2)] = finalString

            os.system("python progressBar.py")
            timelocal = localtime.split(" ")
        #     man = timelocal[2] + "_" +  timelocal[1] + "_" + timelocal[4]
            man = self.dateEdit.date().toPyDate()
            print(man)
            print("IdSelected  " + idSelected)
            sendData = firebase.put("Users/" + idSelected[:-1] + "/",man,dicti2)
            result = firebase.post('Users/' + idSelected[:-1] + "/Dates", data=man, params={'demo': 'demo'})
            print(dicti2)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", name[:-1].upper()))
        self.label_2.setText(_translate("Dialog", idSelected[:-1]))
        self.saveprescriptionbutton.setText(_translate("Dialog", "SAVE PRESCRIPTION"))
        self.label_19.setText(_translate("Dialog", "MEDICINE"))
        self.addWedgets.setText(_translate("Dialog", "ADD"))
        self.deleteWedgets.setText(_translate("Dialog","DELETE"))
        self.label_20.setText(_translate("Dialog", "NAME"))
        self.label_21.setText(_translate("Dialog", "TIME"))
        self.label_22.setText(_translate("Dialog", "QUANTITY"))
        self.label_3.setText(_translate("Dialog", "PATIENT INFO"))
        self.label_4.setText(_translate("Dialog", "PRESCRIPTION DETAILS"))
        self.label_8.setText(_translate("Dialog", "DISEASE NAME"))
        self.label_9.setText(_translate("Dialog", "DATE"))
        self.prescriptionnolabel.setText(_translate("Dialog", "PRESCRIPTION NO - 02"))
        self.prescriptionHistoryutton.setText(_translate("Dialog", "PRESCRIPTION HISTORY"))
        self.nameofpatient.setText(_translate("Dialog", "FULL NAME -"))
        self.namelabel.setText(_translate("Dialog", name[:-1].upper()))
        self.mobilenoofpatient.setText(_translate("Dialog", "MOBILE NO -"))
        self.mobnoLabel.setText(_translate("Dialog", mobileNo[:-1].upper()))
        self.bloodgroup.setText(_translate("Dialog", "BLOOD GROUP -"))
        self.bloodgroupLabel.setText(_translate("Dialog", "O+"))
        #self.address.setText(_translate("Dialog", "ADDRESS -"))
        #self.addresslabel.setText(_translate("Dialog", "N6 CIDECO AURANGABAD"))
        self.label_6.setText(_translate("Dialog", "MEDI-"))
        self.label_5.setText(_translate("Dialog", "CARD"))
        self.label_7.setText(_translate("Dialog", "@ MEDICARD LTD 2020"))

     


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
